### ISSUE TITLE
What hardware is it based on?

### ISSUE THREAD

**Issue by MrTomRod** [ETH-NEXUS/lego_sequencer#4]
Hello!

I want to establish a brick-generation sequencing lab and competence center at my university.

Is this software made for the Blockford Brickopore 5.2 sequencer? What are its advantages over [their software](http://brickopore.co.uk/brickopore-software-installation/)?

![Blockford Brickopore 5.2](https://i1.wp.com/brickopore.co.uk/wp-content/uploads/2019/11/brickopore5_2.png?resize=1536%2C864)

I suggest you add this information to README.md as well.

Best, MrTomRod

**Comment by stekhoven** [comment]
Hi Tom

No, this software was inspired by the original Blockford Brickopore sequencer. We did contact them and asked for permission to recreate the idea with our own design.

We intend to publish construction plans as well as additional documentation, whenever we find some spare time. Including the extension of the readme.md.

Cheers,
Dan
